import { readdirSync, readFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

const currentDir = dirname(fileURLToPath(import.meta.url))
const rootDir = resolve(currentDir, '../..')
const assistantDir = resolve(rootDir, 'supabase/functions/scan-ambiguous-assistant')

function readAssistantFunctionSource() {
  return readdirSync(assistantDir)
    .filter((file) => file.endsWith('.ts'))
    .sort((left, right) => left.localeCompare(right))
    .map((file) => readFileSync(resolve(assistantDir, file), 'utf8'))
    .join('\n')
}

describe('scan ambiguous assistant hardening', () => {
  it('protège la function par auth utilisateur, ownership du scan et statut compatible', () => {
    const file = readAssistantFunctionSource()
    const config = readFileSync(resolve(rootDir, 'supabase/config.toml'), 'utf8')

    expect(file).toContain('const { user, supabase: serviceClient } = await getAuthUser(req)')
    expect(file).toContain('.eq("id", scanId)')
    expect(file).toContain('.eq("user_id", userId)')
    expect(file).toContain('assistant_cache_json')
    expect(file).toContain('assistant_tts_cache_json')
    expect(file).toContain('computeAssistantSourceSignature')
    expect(file).toContain('readAssistantCacheEntry')
    expect(file).toContain('persistAssistantCache')
    expect(file).toContain('reconcileAssistantTtsCacheForLanguage')
    expect(file).toContain('DEFAULT_ASSISTANT_TTS_VOICE')
    expect(file).toContain('.from("assistant-audio")')
    expect(file).toContain('scanContext.productStatus !== "ambiguous"')
    expect(file).toContain('scanContext.productStatus !== "contains_allergen"')
    expect(file).toContain('inferAssistantMode')
    expect(file).toContain('buildHelpfulIngredientLabels')
    expect(file).toContain('splitSelectedCriteria')
    expect(file).toContain('buildAssistantEvidenceMatrix')
    expect(file).toContain('selectedCriteria')
    expect(file).toContain('evidenceMatrix')
    expect(file).toContain('direct_blockers')
    expect(file).toContain('ambiguous_scoped')
    expect(file).toContain('ambiguous_global')
    expect(file).toContain('cleanIngredientDisplayLabel')
    expect(file).toContain('getCompatibilityDescriptor')
    expect(file).toContain('buildMentionExamples')
    expect(file).toContain('sanitizeLineWithFallback')
    expect(file).toContain('sanitizeContextualList')
    expect(file).toContain('buildFallbackResponse')
    expect(file).toContain('buildFallbackAdditionalPhrases')
    expect(file).toContain('callGeminiAdditionalCards')
    expect(file).toContain('mergeStorePhrases')
    expect(file).toContain('MAX_ASSISTANT_CARD_COUNT = 6')
    expect(file).toContain('sanitizeAssistantResponse')
    expect(file).toContain('await persistAssistantCache(')
    expect(file).not.toContain('cache persist skipped')
    expect(file).toContain('Never treat dietary profile labels such as halal, vegan, vegetarian or kosher as ingredients or allergens.')
    expect(file).toContain("Do not ask for an option 'without Halal' or 'without Vegan'. Ask for an option compatible with that profile instead.")
    expect(file).toContain('selected_profile_labels')
    expect(file).toContain('selected_allergen_labels')
    expect(file).toContain('selected_profiles')
    expect(file).toContain('selected_allergen_criteria')
    expect(file).toContain('blocking_labels_clean')
    expect(file).toContain('blocking_mentions_hint')
    expect(file).toContain('primary_criteria_labels')
    expect(file).toContain('assistant_compatibility_descriptor')
    expect(file).not.toContain('function readLatestAssistantResponse(')
    expect(file).toContain('Never output plain language codes like fr or en in user_language.')
    expect(file).toContain('stripRiskTokens')
    expect(file).toContain('Bad French summary:')
    expect(file).toContain('Good French summary:')
    expect(file).toContain('Bad French scoped summary:')
    expect(file).toContain('Good French global ambiguity summary:')
    expect(file).toContain('Good French user_language for Halal/Vegan style profiles:')
    expect(file).toContain("L'étiquette fait apparaître")
    expect(file).toContain('Required JSON shape example:')
    expect(file).toContain('repairing a model output')
    expect(config).toContain('[functions.scan-ambiguous-assistant]\nverify_jwt = false')
  })

  it('charge le sheet Assistant IA pour les scans ambigus et bloquants', () => {
    const page = readFileSync(resolve(rootDir, 'pages/app/scan/[id].vue'), 'utf8')

    expect(page).toContain("import ScanAiAssistantSheet from '~/components/scan/ScanAiAssistantSheet.vue'")
    expect(page).not.toContain('defineAsyncComponent(')
    expect(page).toContain("['ambiguous', 'contains_allergen'].includes(productStatus.value)")
    expect(page).toContain("if (hasAllergenSignals && hasAmbiguousSignals) return 'mixed'")
    expect(page).toContain('showAssistantSheet = true')
    expect(page).toContain('assistant-inline-trigger')
    expect(page).toContain('scan-ai-halo--assistant')
    expect(page).toContain('scan-ai-results-surface')
    expect(page).toContain('<ScanAiAssistantSheet')
    expect(page).toContain('assistant_cache_json')
    expect(page).toContain('initialAssistantData')
    expect(page).toContain("assistantSupportMode.value === 'mixed'")
    expect(page).toContain('.assistant-inline-trigger')
  })

  it('déclenche l appel IA à la demande et laisse le cache persistant au backend', () => {
    const component = readFileSync(resolve(rootDir, 'components/scan/ScanAiAssistantSheet.vue'), 'utf8')

    expect(component).toContain('const { scanAmbiguousAssistant, scanAssistantTts } = useEdgeFunctions()')
    expect(component).toContain('mergeCachedScanAssistant')
    expect(component).toContain("$queryClient?.setQueryData(['scan-detail', props.scanId]")
    expect(component).toContain('assistantCopyKey')
    expect(component).toContain('props.supportMode')
    expect(component).toContain("supportMode: 'ambiguous' | 'allergen' | 'mixed'")
    expect(component).toContain("assistantCopyKey.value === 'mixed'")
    expect(component).toContain("scan.scan.detail.assistant.context_mixed")
    expect(component).toContain('await scanAmbiguousAssistant({')
    expect(component).toContain("language: currentLanguage.value")
    expect(component).toContain('force,')
    expect(component).toContain('analysisRequested')
    expect(component).toContain('initialAssistantData')
    expect(component).toContain('applyInitialAssistantData')
    expect(component).toContain('appendAssistantCards')
    expect(component).toContain("t('scan.scan.detail.assistant.btn_add_cards')")
    expect(component).toContain("{{ t('scan.scan.detail.assistant.btn_start') }}")
    expect(component).toContain('h-[80vh]')
    expect(component).not.toContain('assistant-intro-note')
    expect(component).not.toContain('void loadAssistant(false)')
    expect(component).not.toContain('useQuery(')
  })

  it('ajoute une lecture TTS japonaise a la demande, sans prefetcher tous les audios', () => {
    const component = readFileSync(resolve(rootDir, 'components/scan/ScanAiAssistantSheet.vue'), 'utf8')
    const edgeFunctions = readFileSync(resolve(rootDir, 'composables/useEdgeFunctions.ts'), 'utf8')

    expect(component).toContain('await scanAssistantTts({')
    expect(component).toContain('phrase_index: index')
    expect(component).toContain('language: currentLanguage.value')
    expect(component).toContain('new Audio(audioUrl)')
    expect(component).toContain('assistant-copy-btn--icon')
    expect(component).toContain('getAudioButtonLabel')
    expect(component).toContain("audio.preload = 'auto'")
    expect(component).not.toContain('void scanAssistantTts(')

    expect(edgeFunctions).toContain("callEdgeFunction<ScanAssistantTtsResponse>('scan-assistant-tts'")
  })

  it('passe un flag force dans le contrat assistant pour permettre une regeneration reelle', () => {
    const edgeFunctions = readFileSync(resolve(rootDir, 'composables/useEdgeFunctions.ts'), 'utf8')
    const sharedTypes = readFileSync(resolve(rootDir, 'supabase/functions/_shared/scan-ai-assistant.ts'), 'utf8')
    const assistantFunction = readFileSync(resolve(rootDir, 'supabase/functions/scan-ambiguous-assistant/index.ts'), 'utf8')

    expect(sharedTypes).toContain('force?: boolean')
    expect(sharedTypes).toContain('append_cards?: boolean')
    expect(edgeFunctions).toContain('force: payload.force ?? false')
    expect(edgeFunctions).toContain('append_cards: payload.append_cards ?? false')
    expect(assistantFunction).toContain('regenerationAttempt')
    expect(assistantFunction).toContain('areAssistantResponsesMeaningfullyDifferent')
    expect(assistantFunction).toContain('buildDistinctForcedAssistantFallback')
    expect(assistantFunction).toContain('Regeneration remained too close to the cached answer')
  })
})
